import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/skresultat">Skresultat</Link>
        </li>
        <li>
          <Link to="/arkiv">Arkiv</Link>
        </li>
        <li>
          <Link to="/inloggadkund">Inloggadkund</Link>
        </li>
        <li>
          <Link to="/skapakonto">Skapakonto</Link>
        </li>
        <li>
          <Link to="/inloggningssida">Inloggningssida</Link>
        </li>
        <li>
          <Link to="/">Startsida</Link>
        </li>
        <li>
          <Link to="/laddauppbild">Laddauppbild</Link>
        </li>
        <li>
          <Link to="/varukorg">Varukorg</Link>
        </li>
        <li>
          <Link to="/valdbild">Valdbild</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
